apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: e-comm

resources:
- ../../../base/
- deployment.yaml
- service.yaml

configMapGenerator:
- behavior: merge
  envs:
  - configMap.properties
  name: config-map
images:
- name: list_products
  newName: list_products
  newTag: main.13
