apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: e-comm

resources:
  - ../../../base/
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: config-map
    behavior: merge
    envs:
      - configMap.properties